### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [Matt--L/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Matt--L** [comment]
I think this is what you are talking about. This allows the user to use touch zoom and helps with rendering correctly on mobile.

<meta name="viewport" content="width=device-width, initial-scale=1">

**Comment by MarcoMorawec** [comment]
@Matt--L Make sure you refer to the [correct commit](https://github.com/Matt--L/splurty/commit/a99ae2b1469987310aac104ebdc8842fc7170e30) where you included your mobile meta tag, so others can easily check your code :)

:+1: and nice job :)

Make sure you close this issue now that you're done.

**Comment by Matt--L** [comment]
Added mobile meta tag <a href="https://github.com/Matt--L/splurty/commit/a99ae2b1469987310aac104ebdc8842fc7170e30">here</a>.
